Using facedetection on images:  38%|███████████████████████████████████████████████▌                                                                             | 1758/4624 [4:07:43<6:43:51,  8.45s/it]
Traceback (most recent call last):
  File "/work/VictorRasmussen#3454/cds.vis/cds-vis/assignment4/src/1.py", line 142, in <module>
    results = image_processing(images)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/VictorRasmussen#3454/cds.vis/cds-vis/assignment4/src/1.py", line 107, in image_processing
    boxes, _ = mtcnn.detect(images[i])
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ucloud/.local/lib/python3.12/site-packages/facenet_pytorch/models/mtcnn.py", line 313, in detect
    batch_boxes, batch_points = detect_face(
                                ^^^^^^^^^^^^
  File "/home/ucloud/.local/lib/python3.12/site-packages/facenet_pytorch/models/utils/detect_face.py", line 40, in detect_face
    imgs = np.stack([np.uint8(img) for img in imgs])
                     ^^^^^^^^^^^^^
  File "/home/ucloud/.local/lib/python3.12/site-packages/PIL/Image.py", line 681, in __array_interface__
    new["data"] = self.tobytes()
                  ^^^^^^^^^^^^^^
  File "/home/ucloud/.local/lib/python3.12/site-packages/PIL/Image.py", line 740, in tobytes
    self.load()
  File "/home/ucloud/.local/lib/python3.12/site-packages/PIL/ImageFile.py", line 288, in load
    raise OSError(msg)
OSError: image file is truncated (174 bytes not processed)